promo code applied for login 50%off on bid amount
souravjaisingh/VibeSyncApp pull request #277
Opened 2024-08-07 05:04 UTC by siddharth05092004

2024-08-07 07:08 UTC, souravjaisingh approved these changes

2024-08-07 07:10 UTC, souravjaisingh commented on VibeSyncApp/ClientApp/src/components/PaymentIndex.js
> +          rowData_to_change.minimumBid = Math.round(rowData.minimumBid/2)
We don't have to make minimum bid / 2. It should stay same. A new label should appear however, just like GST, which shows the discount applied. And Amount on Pay button should reflect that.

2024-08-07 07:10 UTC, souravjaisingh requested changes
We don't have to make minimum bid / 2. It should stay same. A new label should appear however, just like GST, which shows the discount applied. And Amount on Pay button should reflect that.

2024-08-07 20:07 UTC, bhavikmittal requested changes
Address the comments

2024-08-08 05:07 UTC, siddharth05092004 commented
Will do it today.

2024-08-08 08:55 UTC, closed without merging